### ISSUE TITLE
.NET 6 should be added as a library target

### ISSUE THREAD

**Issue by davebronson** [davebronson/clear-hl7-net#34]

**Comment by Px-APhillips** [comment]
Hi, 
I can see there was a branch for adding .NET6 support, any reason this was stalled as an update or is it just in the roadmap to add?
Thanks

**Comment by davebronson** [comment]
Hi Adam.  I was waiting, at this point, until .NET 7 is released so that I could add targets for both 6 and 7 at the same time.  No reason other than that.  If it would be helpful, I can merge this change in now and get the NuGet package updated?

**Comment by Px-APhillips** [comment]
> Hi Adam. I was waiting, at this point, until .NET 7 is released so that I could add targets for both 6 and 7 at the same time. No reason other than that. If it would be helpful, I can merge this change in now and get the NuGet package updated?

That's good to know. It's not imperative at the moment as we are assessing options to assist with HL7 parsing. Our baseline at the moment is NET6 due to its LTS status but knowing that it's coming is fine. Thanks
